### ISSUE TITLE
Proxy classes filenames in tmp

### ISSUE THREAD

**Issue by sts85** [graphaware/neo4j-php-ogm#107]
The proxy classes for Database entities are stored in php tmp dir with the following naming convention:

neo4j_ogm_proxy_{NAMESPACE}_{CLASSNAME}.php

If I have different installations on one machine (e.g., dev, staging, production or different client installations), deployment of one installation will affect all other installations (as it happened in my case).

So the better solution would be to add a unique id to the end of the file name in order to avoid problems.

**Comment by ikwattro** [comment]
@sts85 The proxy directory is configurable, wouldn't it help to use a different directory depending on your environments ?

**Comment by ikwattro** [comment]
@sts85 can this be closed?

**Comment by sts85** [comment]
Right, that would work as well. I did not see that it is configurable. Thanks
