### ISSUE TITLE
NodeEntityMetadata->getAssociatedObjects misleading and/or redundant

### ISSUE THREAD

**Issue by AndrolGenhald** [graphaware/neo4j-php-ogm#12]
From it's name I can't really tell what it's supposed to do. If anything, I would expect it to return `$this->relationships` instead of `$this->getSimpleRelationships()`, but either way it's redundant.

**Comment by ikwattro** [comment]
It is redundant, this was used before releationship entities were in place. Now lets be honest, the `BaseRepository` and `UnitOfWork` classes need a huge refactoring, I just wanted to reach a state where I know what I need where for what.

I think I almost reached it, another user has tested the ogm heavily on an existing application and lot of bugs were fixed.

The next big step is moving the relationships fetching + hydration in their own logic, this will offer possibilities like fine grained order and pagination.

**Comment by ikwattro** [comment]
@AndrolGenhald Maybe it would make sense to implement the ClassMetadata interfaces from Doctrine Common. I see the benefits of it and might change that during the weekend.

**Comment by AndrolGenhald** [comment]
@ikwattro Funny you should mention that, I was in the process of doing that and that's why I noticed the getAssociatedObjects method in the first place. It looks like most of the methods are fairly straightforward, but I'm not sure what all of them are supposed to return, I just got enough of the easy ones implemented for the DoctrineModule form elements to work.

**Comment by ikwattro** [comment]
Very cool, you might maybe open a PR already, so we don't overlap efforts. If you are active on the neo4j-users slack you can connect also with me there `chris.graphaware`

**Comment by ikwattro** [comment]
@AndrolGenhald There is a branch now `doctrine-metadata` where the class metadata now implements Doctrine ClassMetadata.

**Comment by AndrolGenhald** [comment]
That was quick! The one thing I wasn't sure about was `getName`, the interface says it should return a FQCN, but is `$this->className` guaranteed to be fully qualified?

**Comment by ikwattro** [comment]
Yes, when the metadata factory build the GraphEntityMetadata it receives a fqcn, otherwise it will throw a class not found

**Comment by ikwattro** [comment]
@AndrolGenhald Are you happy that I merge the metadata branch in master and you rebase on it, or do you think you can have conflicts with that ?

**Comment by AndrolGenhald** [comment]
@ikwattro That's fine, unfortunately I don't think I have anything to add. The only thing I see that's different is that I used `array_keys` and `in_array` a couple places instead of looping.

**Comment by ikwattro** [comment]
Right, I'll merge then and make a new release.
