### ISSUE TITLE
entityManager->createQuery() result improvements

### ISSUE THREAD

**Issue by theUm** [graphaware/neo4j-php-ogm#120]
It would be good if createQuery will support `collect()` cypher syntax and non-Node result parameters. Basically we need to merge new QueryResultMapping that supports inly nodes with old one, that supported  basic types.

**Comment by ikwattro** [comment]
It should be supported, the only thing is that you would get for now a raw result instead. But yes some improvements will come for sure.

**Comment by ikwattro** [comment]
Fixed by #125

**Comment by ikwattro** [comment]
I shipped it in RC4, updated documentation : 

http://neo4j-php-ogm.readthedocs.io/en/latest/getting_started/tutorial/#using-custom-cypher-queries

**Comment by theUm** [comment]
Thank you, very helpful.
