### ISSUE TITLE
Attempted to call an undefined method named "__setNode" of class "__PHP_Incomplete_Class".

### ISSUE THREAD

**Issue by sts85** [graphaware/neo4j-php-ogm#122]
Since RC-1 (and continuing to exist in RC-3), I have a very odd problem coming up, which I cannot really reproduce and it occurs seemingly randomly on various operations.

I am using Symfony 3.2 stack with neo4j-php-ogm (RC-3).

The error occurs in various scenarios, for example, when calling a getter of a lazy relationship collection:

    $person->getLikes();

Where Person.likes is defined as follows

    /**
     * @OGM\Relationship(type="LIKES", direction="OUTGOING", 
     *      targetEntity="Like", collection=true)
     * @OGM\OrderBy(property="dateLiked", order="ASC")
     *
     * @var ArrayCollection|Like[]
     */
    protected $likes;

But also when calling findOneBy()

    $em->getRepository(Module::class)->findOneBy(['name' => 'foobar']);

So far I was not able to determine the pattern when and how this occurs, I just increased debugging in my project and will report in more details once I have found out some more. Just wanted to report the issue in case others have the same issue. This is an example stack trace when the error occurs from the latter of the upper examples.

    {
    "class": "Symfony\\Component\\Debug\\Exception\\UndefinedMethodException",
    "message": "Attempted to call an undefined method named \"__setNode\" of class \"__PHP_Incomplete_Class\".",
    "code": 0,
    "file": "var/myProject/vendor/graphaware/neo4j-php-ogm/src/Proxy/ProxyFactory.php:37",
    "trace": [
        "var/myProject/vendor/graphaware/neo4j-php-ogm/src/UnitOfWork.php:1009",
        "var/myProject/vendor/graphaware/neo4j-php-ogm/src/UnitOfWork.php:785",
        "var/myProject/vendor/graphaware/neo4j-php-ogm/src/Hydrator/EntityHydrator.php:276",
        "var/myProject/vendor/graphaware/neo4j-php-ogm/src/Hydrator/EntityHydrator.php:52",
        "var/myProject/vendor/graphaware/neo4j-php-ogm/src/Persisters/BasicEntityPersister.php:50",
        "var/myProject/vendor/graphaware/neo4j-php-ogm/src/Repository/BaseRepository.php:94",
        "var/myProject/src/Jbo/Neo4jBundle/Repository/ModuleRepository.php:25",
        "var/myProject/var/cache/prod/classes.php:4898",
        "var/myProject/var/cache/prod/classes.php:4202",
        "var/myProject/var/cache/prod/classes.php:4889",
        "var/myProject/var/cache/prod/classes.php:4143",
        "var/myProject/var/cache/prod/classes.php:4641",
        "var/myProject/var/cache/prod/classes.php:4607",
        "var/myProject/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:168",
        "var/myProject/web/app.php:43"
    ]
    }

**ProxyFactory on Line 37**

    $object = $this->createProxy();
    $object->__setNode($node);

    // Debugging the object variable:
    var_dump($object);

Output

    __PHP_Incomplete_Class Object
    (
       [__PHP_Incomplete_Class_Name] => neo4j_ogm_proxy_Jbo_Neo4jBundle_Entity_Module
    )

**Comment by ikwattro** [comment]
Hi @sts85 , I encountered the same issue when being in debug mode. It seems it is related to sessions, generally refreshing the page makes the call ok. I will investigate further though.

**Comment by ikwattro** [comment]
@sts85 It seems I might have found a starting point : 

https://github.com/symfony/symfony/issues/3907

https://github.com/doctrine/DoctrineMongoDBBundle/pull/85/files

**Comment by ikwattro** [comment]
@sts85 So good news.

I made a quick test with the mentioned issues/PR on the ORM's/ODM's as reference and it seems to work.

```php
<?php

namespace AppBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class AppBundle extends Bundle
{
    private $autoloader;

    public function boot()
    {
        $container = &$this->container;

        $this->autoloader = function($class) use (&$container) {
            if (0 === strpos($class, 'neo4j_ogm_proxy')) {
                $cacheDir = $container->getParameter('kernel.cache_dir') . DIRECTORY_SEPARATOR . 'neo4j';
                $file = $cacheDir.DIRECTORY_SEPARATOR.$class.'.php';
                if (file_exists($file)) {
                    require_once $file;
                }
            }
        };

        spl_autoload_register($this->autoloader);
    }

    public function shutdown()
    {
        spl_autoload_unregister($this->autoloader);
    }
}
```

However this has nothing to do with the ogm itself but rather the symfony bundle going with it. This would require though maybe some configuration here.

I will port this issue to the neo4j-symfony bundle

**Comment by Sraime** [comment]
something new ?  :/

**Comment by ikwattro** [comment]
This hasn't been implemented in the Symfony bundle yet but as I said you can easily fix it on your side. This has nothing to do with the ogm itself.

**Comment by theUm** [comment]
//offtopic @ikwattro  plz see my merge pull request for symfony bundle
https://github.com/ikwattro/neo4j-symfony/pull/1
that branch should be merged into master, and version tag should be updated for proper install via composer. composer installs by default version with tag 0.3 that still contains that typo in profiler view.

**Comment by ikwattro** [comment]
@theUm I don't understand why you make a PR on my fork? Also I added this already in the official repo https://github.com/neo4j-contrib/neo4j-symfony/pull/22

**Comment by theUm** [comment]
ok. Sorry, I`m quite new with github forks\PRs, so now I see that PR my pr is useless. BUT try to make clear install throught composer, you will get 0.3 tag in which there is a bug in twig:
latest master reference: https://github.com/neo4j-contrib/neo4j-symfony/blob/master/Resources/views/webprofiler.html.twig#L87
0.3 tag reference: https://github.com/neo4j-contrib/neo4j-symfony/blob/0.3.0/Resources/views/webprofiler.html.twig#L87

**Comment by cebe** [comment]
As this never happened to me locally and happens very often on the server I assume a race condition in `ProxyFactory`, which is similar to what is described here: http://php.net/manual/en/function.file-put-contents.php#112831

As far as I see the problem occurs when the class does not exist when unserializing, however there is a require statement that includes the file, so this should never happen:

https://github.com/graphaware/neo4j-php-ogm/blob/a4e2b755c4551679056668802a0dd743e890d7f6/src/Proxy/ProxyFactory.php#L132-L136

the only case where I see this could happen is that two parallel processes are running the same code at the same time and while one is reading the file, the other is running `file_put_contents` which just recreated the file with empty content, so `require` does not define the class.

I have not verifed that this is the case but it seems very likely and the code in `ProxyFactory` should be adjusted to avoid this problem.

**Comment by ikwattro** [comment]
@cebe You mean that you get this on the server 

```
Attempted to call an undefined method named "__setNode" of class "__PHP_Incomplete_Class".
```
?

**Comment by cebe** [comment]
@ikwattro I have not implemented the autoloader from your comment as it should not be necessary. The proxy class is calling `require` so there should be no need for the autoloader, if `require` works correctly.

I get the following error on a server in `prod` environment:

```
Error: Call to undefined method __PHP_Incomplete_Class::__setNode() in /var/www/backoffice/vendor/graphaware/neo4j-php-ogm/src/Proxy/ProxyFactory.php:37
Stack trace:
#0 /var/www/backoffice/vendor/graphaware/neo4j-php-ogm/src/UnitOfWork.php(1025): GraphAware\Neo4j\OGM\Proxy\ProxyFactory->fromNode(Object(GraphAware\Bolt\Result\Type\Node))
#1 /var/www/backoffice/vendor/graphaware/neo4j-php-ogm/src/UnitOfWork.php(801): GraphAware\Neo4j\OGM\UnitOfWork->newInstance(Object(GraphAware\Neo4j\OGM\Metadata\NodeEntityMetadata), Object(GraphAware\Bolt\Result\Type\Node))
#2 /var/www/backoffice/vendor/graphaware/neo4j-php-ogm/src/Hydrator/EntityHydrator.php(262): GraphAware\Neo4j\OGM\UnitOfWork->createEntity(Object(GraphAware\Bolt\Result\Type\Node), 'Jbo\\Neo4jBundle...', 936978)
#3 /var/www/backoffice/vendor/graphaware/neo4j-php-ogm/src/Hydrator/EntityHydrator.php(102): GraphAware\Neo4j\OGM\Hydrator\EntityHydrator->hydrateNode(Object(GraphAware\Bolt\Result\Type\Node), 'Jbo\\Neo4jBundle...')
#4 /var/www/backoffice/vendor/graphaware/neo4j-php-ogm/src/Persisters/BasicEntityPersister.php(104): GraphAware\Neo4j\OGM\Hydrator\EntityHydrator->hydrateSimpleRelationshipCollection('addresses', Object(GraphAware\Bolt\Result\Result), Object(neo4j_ogm_proxy_Jbo_Neo4jBundle_Entity_Coin_CoinVault))
#5 /var/www/backoffice/vendor/graphaware/neo4j-php-ogm/src/Proxy/NodeCollectionInitializer.php(22): GraphAware\Neo4j\OGM\Persisters\BasicEntityPersister->getSimpleRelationshipCollection('addresses', Object(neo4j_ogm_proxy_Jbo_Neo4jBundle_Entity_Coin_CoinVault))
#6 /var/www/backoffice/vendor/graphaware/neo4j-php-ogm/src/Proxy/LazyCollection.php(52): GraphAware\Neo4j\OGM\Proxy\NodeCollectionInitializer->initialize(Object(GraphAware\Bolt\Result\Type\Node), Object(neo4j_ogm_proxy_Jbo_Neo4jBundle_Entity_Coin_CoinVault))
#7 /var/www/backoffice/vendor/doctrine/collections/lib/Doctrine/Common/Collections/AbstractLazyCollection.php(332): GraphAware\Neo4j\OGM\Proxy\LazyCollection->doInitialize()
#8 /var/www/backoffice/vendor/doctrine/collections/lib/Doctrine/Common/Collections/AbstractLazyCollection.php(274): Doctrine\Common\Collections\AbstractLazyCollection->initialize()
#9 /var/www/backoffice/src/Jbo/Neo4jBundle/Entity/Coin/AbstractCoinVault.php(188): Doctrine\Common\Collections\AbstractLazyCollection->getIterator()
#10 /var/www/backoffice/src/Jbo/CoinBundle/Cronjobs/UnfreezeCoinsCronjob.php(75): Jbo\Neo4jBundle\Entity\Coin\AbstractCoinVault->getBalanceMoney()
#11 [internal function]: Jbo\CoinBundle\Cronjobs\UnfreezeCoinsCronjob->run()
#12 /var/www/backoffice/src/Jbo/CoreBundle/Cron/CronjobProcessor.php(240): call_user_func(Array)
#13 /var/www/backoffice/src/Jbo/CoreBundle/Command/CronjobIsolationCommand.php(62): Jbo\CoreBundle\Cron\CronjobProcessor->runClass(Object(neo4j_ogm_proxy_Jbo_CoreBundle_Cron_Db_CronjobTask))
#14 /var/www/backoffice/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(252): Jbo\CoreBundle\Command\CronjobIsolationCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/backoffice/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(954): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/backoffice/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRunCommand(Object(Jbo\CoreBundle\Command\CronjobIsolationCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/backoffice/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(240): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Jbo\CoreBundle\Command\CronjobIsolationCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/backoffice/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/backoffice/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/backoffice/bin/console(28): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#21 {main}
```

**Comment by ikwattro** [comment]
Well other mappers also use require and this solution has been implemented in the doctrine odm and phpcr-odm as well.

**Comment by esynaps** [comment]
> Attempted to call an undefined method named "__setNode" of class "__PHP_Incomplete_Class".

I implemented the solution provided in the bundle boot method and I still have this error that appears randomly on my server, not on local

**Comment by cebe** [comment]
They use require, but they do not generate the file on every call, which avoids the problem with overwriting it while it is being read:

https://github.com/doctrine/common/blob/a3e240fa07ec9748387c13534949d543c0e177fa/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php#L211-L243

**Comment by cebe** [comment]
I just deployed this change to our server, as far as I see it should fix the problem.

https://github.com/cebe/neo4j-php-ogm/commit/040abb4028bda2d94f4b5cce6057646eac3ffd31

Will report back later.

**Comment by cebe** [comment]
After applying the patch the error is gone, while I have seen it a dozen times per hour before, I have not seen a single instance since this morning. We should either apply a locking as I have implemented or do something similar to doctrine, which will avoid overriding the file every time we call the method, but only write it if it does not exist, this would also improve io in production.

**Comment by ikwattro** [comment]
Added the autoloader to the symfony bundle as well. 

https://github.com/neo4j-contrib/neo4j-symfony/pull/40
