### ISSUE TITLE
RC4 Issue with deleting simple relationship

### ISSUE THREAD

**Issue by JoeThielen** [graphaware/neo4j-php-ogm#126]
Let's say I have object A and object B.  Object A implements a collection of Object Bs (many), but a B can only map back to one A.    I want to remove the relationship between A and B.  The relationship is simple, no relationship entity involved.

In RC3 it didn't matter if I set B's relationship to A null first or if I removed B from A's collection.  
In RC4 it does... if I just set B's relationship to A as null, it seems as if when I remove B (by calling A->getBs()->removeElement(A) it might be re-doing B's relationhship to A, causing the whole delete process to not actually work.  

But, in RC4, if I do remove the item from the collection FIRST, then it does work.  

I could not find a suitable unit test that closely matched this situation.  I don't think you have a test with a one-to-many relationship that only uses simple relationships and not relationship entities.

I remember there were some notes made about this.  But I think that had to do with calling the getters before the setters.  I'm not saying this is a show-stopper or anything, because as long as I recognize this is an issue I can just make sure to do the right order.  But it's weird that it worked in RC3 then changed in RC4.

**Comment by ikwattro** [comment]
Interesting, there is nothing in RC4 that has been changed in the code regarding this.

For the tests, there is here : https://github.com/graphaware/neo4j-php-ogm/blob/master/tests/Integration/EntityWithSimpleRelationshipCollectionTest.php

This is actually a 1..m mapping, one Building having multiple floors.

I will add a m..1 test to be sure.

**Comment by ikwattro** [comment]
Hi @JoeThielen . Thanks for raising this issue. Having such quick feedback makes the OGM better every day. 

So it is fixed and will ship in RC5. However the line of code involved didn't change since 2 months following git blame, so I guess this issue is there since long time :)

**Comment by JoeThielen** [comment]
Looks good!  

If I downgrade to RC3 the issue went away.  Moving to RC4 introduced the error.  So something had a bad interaction.  Regardless, thanks very much for taking the time to look into it and fix it.  I didn't have enough time yesterday afternoon to take a full look at the tests you pointed to.  I did look at the models and yeah, those looked about perfect for this particular situation.  But shortly after you had it fixed anyway!
