### ISSUE TITLE
Find by id problem

### ISSUE THREAD

**Issue by marius-dev** [graphaware/neo4j-php-ogm#134]
Hi!,

I'm trying to find an entity by _id_, but if that _id_ corresponds to another entity with similar properties, the result have the type of the desired entity, but the data of a different one.

Let's say we have the following entities:

`class A{
    $id;
    $x;
    $y;
}`
and 
`class B{
    $id;
    $x;
    $y;
}`

If in db, is stored only one node with label _**A**_, with the $id: _211_ ,  $x = 'test_a', $y = 'test_a' and I make the following call 
`        $b= $this->getEntityManager()
            ->getRepository(B:class)
            ->findOneById(211);
`
$b would not be null, and will have the same values as that node, and if I try to remove $b:

`        $this->getEntityManager()->remove($b, true);
        $this->getEntityManager()->flush();`

, that nod with the label _**A**_ would be removed.

How can I avoid that?

**Comment by ikwattro** [comment]
I've hard to understand what you exactly means. `findOneById()` is meant to search by *neo4j internal id* , not by a property called id.

Is it that doing a findOneById is returning a node with another label (so no check on the label is done to know if it can hydrate this node to a B:class object ) ?

**Comment by marius-dev** [comment]
Form what I've seen in `getMatchOneByIdCypher($id)` form _ BasicEntityPersister_  a query like `MATCH (identifier) WHERE id(identifier) = {id} RETURN identifier` is generated, but I think it should be something like this:   `MATCH (identifier:ClassLabel) WHERE id(identifier) = {id} RETURN identifier`

**Comment by ikwattro** [comment]
You are right. Opened relevant issue here : https://github.com/graphaware/neo4j-php-ogm/issues/135

**Comment by ikwattro** [comment]
Thanks @marius-dev , issue fixed on master branch
