### ISSUE TITLE
Call to a member function isCollection() on null

### ISSUE THREAD

**Issue by marius-dev** [graphaware/neo4j-php-ogm#140]
I'm trying to serialize a collection of objects taken from db and get the following error:

> Call to a member function isCollection() on null

> **on** vendor/graphaware/neo4j-php-ogm/src/Hydrator/EntityHydrator.php",
                        "line": 81,

Each object is made up of several objects and object collections. What could be the problem?

**Comment by oliver-schulz** [comment]
Did you add `$this->property = new Collection();` to your __constructor? You have to initialize your properties first.

**Comment by marius-dev** [comment]
I'm pretty sure I've initialized all the collections.
The problem arises on ManuToMany relationships, where each entity contains a collection of the other entity type.
To avoid "circular reference problem" at serialization I create a normalizer like tihis: 

`class Normalizer extends ObjectNormalizer {
    public function __construct(ClassMetadataFactoryInterface $classMetadataFactory = null, NameConverterInterface $nameConverter = null, PropertyAccessorInterface $propertyAccessor = null, PropertyTypeExtractorInterface $propertyTypeExtractor = null) {        
        parent::__construct($classMetadataFactory, $nameConverter, $propertyAccessor, $propertyTypeExtractor);
        $this->setCircularReferenceHandler(function ($object) {
            return $object->getId();
        });
    }
}`

After one layer, this Normalizer replece the reference to it's id.

**Comment by ikwattro** [comment]
would you be able to provide a link to a test ?
