### ISSUE TITLE
When creating a Relationship the definition of mapping should be camelCase.

### ISSUE THREAD

**Issue by CristianSitov** [graphaware/neo4j-php-ogm#146]
I was trying to create a relationship between Resource & ClassificationType.
```php
class ClassificationType {
    /**
     * @var Resource
     * @OGM\Relationship(type="HasClassificationType",... mappedBy="resource")
     */
   protected $resource;
}
class Resource {
    /**
     * @var Resource
     * @OGM\Relationship(type="HasClassificationType",... mappedBy="classification_type")
     */
   protected $classification_type;
}
```

Apparently, for the latter, I should be using:
```php
class Resource {
    /**
     * @var Resource
     * @OGM\Relationship(type="HasClassificationType",... mappedBy="classificationType")
     */
   protected $classification_type;
}
```
basically, instead of attribute `mappedBy` having `classification_type` it should have `classificationType`.

I'm assuming the problem starts in the ProxyFactory, in the `getMethodProxies()` method:
```php
            $getter = 'get'.ucfirst($relationship->getPropertyName()).'()';
            $g = 'get'.ucfirst($relationship->getPropertyName());
```
where the faulty `classification_type` naming generates something like `getClassification_type` instead of `getClassificationType`.

**Comment by ikwattro** [comment]
Yes, this is not mentioned but method names must be in camelCase as described in PSR-1. I will add an addition to the doc for it.
