### ISSUE TITLE
No Session Registered Supporting Version and Undefined Index: success

### ISSUE THREAD

**Issue by emhohensee** [graphaware/neo4j-php-ogm#162]
I've just installed the neo4j-php-ogm package along with the neo4j-symfony package into a brand new Symfony web application using Composer.

Versions:
PHP 7.1.10
Symfony 3.3.10
Neo4j 3.3.0

I'm seeing two two errors simultaneously when accessing the path for this route:
```
    /**
     * @Route("/graphs", name="graphs")
     */
    public function graphAction(Request $request)
    {
        $em = $this->container->get('neo4j.entity_manager.default');
        $fronts = $em->getRepository(Front::class)->findAll();
        var_dump($fronts);
    }
```
The first is an `InvalidArgumentException` stating `No session registered supporting Version 1213486160`. The second is a `ContextErrorException` stating `Notice: Undefined index: success`. Other than the Neo4j configs in my YAML files, I haven't added anything else to the project. Is this a version number issue with Symfony?

**Comment by emhohensee** [comment]
I figured out from another ticket that I specified the Bolt scheme but gave the HTTP port. Seeing an authorization error now I'm sure that's on me. Closing issue.

**Comment by ikwattro** [comment]
Thanks. Unfortunately the error from the neo4j server is not really straight forward, we could maybe try to be proactive and detect on the client level by parsing the given uri if people try to use bolt with the default http port.
