### ISSUE TITLE
Can't register event listener from services.yml

### ISSUE THREAD

**Issue by amiriskander** [graphaware/neo4j-php-ogm#183]
I'm not sure if I'm missing something here, I'm trying to register an event listener from services.yml but I'm not able to, I think I may be using the wrong event, or wrong tag name.

```
    MyVendor\MyBundle\EventListener\NodeListener:
        tags:
            - { name: kernel.event_listener, event: preFlush, method: preFlush }
```

Registering the event listener using the way described in [this answer](https://stackoverflow.com/a/42169248) is perfectly fine but I should be able to register it from services.yml

**Comment by ikwattro** [comment]
There is no support for this, simply because this package is not Symfony specific.

You might better of port your feature request to https://github.com/neo4j-contrib/neo4j-symfony
