### ISSUE TITLE
Using a QueryBuilder to manage OR clauses

### ISSUE THREAD

**Issue by Luciam91** [graphaware/neo4j-php-ogm#19]
Found this library and it's allowing me to get my head round Neo4J a bit better, so thanks for that!

I've used Doctrine for a while and regularly use the query builder to build up datasets based on OR conditions in a SQL query (movie = 'The Matrix' OR movie='Finding Dory')

This may not be possible in Neo4J (i'm still learning as I go), but if it is. Is it possible with this library to do these complex matches?

Another example I'm looking at is getting an object depending on whether 1 of 2 properties is equal to a value

**Comment by mikaelmattsson** [comment]
>For questions, please open a new thread on [StackOverflow](https://stackoverflow.com) with the `graphaware`, `neo4j` and `neo4j-php-ogm` tags.

`OR` is not a complex match and something Neo4j is able to do.

**Comment by Luciam91** [comment]
Thanks for that! Back to my object drawing board :D
