### ISSUE TITLE
Hide property

### ISSUE THREAD

**Issue by m33ch** [graphaware/neo4j-php-ogm#29]
Hi all,

thanks for this package! 

I wonder if there is an annotation to hide the property. 
For example `password`.

Is it possible?

Thanks

**Comment by ikwattro** [comment]
If you don't want to map the property back to your domain, you just don't annotate it, but then any changes will not be reflected. 

Other than that, this library doesn't return anything directly to the frontend or any other part of the application, so this logic actually should be implemented by you.
