### ISSUE TITLE
Multiple properties with the same relation ship name

### ISSUE THREAD

**Issue by mikaelmattsson** [graphaware/neo4j-php-ogm#3]
I don't know if this is a bug or a feature request.

I can't have two properties with the same relationship name.
```
Type mismatch: rel_in_love_with already defined with conflicting type Collection<T> (expected Relationship) (line 3, column 22 (offset: 276))
"OPTIONAL MATCH (n)<-[rel_in_love_with:IN_LOVE_WITH]-(lovedBy) WITH n, rel_in_love_with, CASE count(rel_in_love_with) WHEN 0 THEN [] ELSE collect({start:startNode(rel_in_love_with), end:endNode(rel_in_love_with), rel:rel_in_love_with}) END as rel_in_love_with"
```

```
/**
 * @OGM\Relationship(type="IN_LOVE_WITH", direction="OUTGOING", targetEntity="User", collection=true)
 */
protected $loves;

/**
 * @OGM\Relationship(type="IN_LOVE_WITH", direction="INCOMING", targetEntity="User", collection=true)
 */
protected $lovedBy;
```

Also “BOTH” as a direction is referenced in the docs but not yet implemented.

**Comment by ikwattro** [comment]
@mikaelmattsson I'll have a look at it tonight, normally this should work, I'll write an integration test for that and fix.

For the second, you're right it is not yet implemented, this might require a bit more time to implement in order to be sure to not return duplicates.

**Comment by ikwattro** [comment]
@mikaelmattsson 

I have pushed a first implementation, based on this model class : 

https://github.com/graphaware/neo4j-php-ogm/blob/1.0/tests/Integration/Model/User.php#L35

And the test is actually here : 

https://github.com/graphaware/neo4j-php-ogm/blob/1.0/tests/Integration/RelationshipIntegrationTest.php#L135

Note : 

There is a `mappedBy` parameter in the annotation, that permits to distinct to which property the found related nodes should be mapped.

Todo: same for non-collection relationships and relationship entities

**Comment by ikwattro** [comment]
@mikaelmattsson 1.0.0-beta3 released

**Comment by mikaelmattsson** [comment]
COOL!
