### ISSUE TITLE
get_parent_class should be checked for false value in GraphEntityMetadataFactory

### ISSUE THREAD

**Issue by wrgx** [graphaware/neo4j-php-ogm#45]
GraphAware\Neo4j\OGM\Metadata\Factory\GraphEntityMetadataFactory::create should check for existence of parent class comparing function return value to false, not to null. See [doc](http://php.net/manual/en/function.get-parent-class.php).

**Comment by ikwattro** [comment]
Nice ! Thx

**Comment by ikwattro** [comment]
Fixed
