### ISSUE TITLE
Properties of type "array" not working

### ISSUE THREAD

**Issue by kbsali** [graphaware/neo4j-php-ogm#47]
We have a user entity extending the fosuser model (yeah, we shouldn't!),
and we are having issues with the `roles` property. Here is the definition (pretty similar to the `Role` relationship example of this repo)  : 

```php
<?php

namespace OGMEntityBundle\Entity;

/**
 * @OGM\Node(label="User", repository="OGMEntityBundle\Repository\Repository")
 */
class User extends BaseUser implements UserInterface
{


    /**
     * @var array
     * @OGM\Property(type="array")
     */
    protected $roles = [];

   ...

    /**
     * @return mixed
     */
    public function getRoles()
    {
        return $this->roles;
    }
    public function setRoles(array $roles)
    {
        $this->roles = $roles;
    }
}
```

And when trying to persist that entity we get : 

```
Neo4j Exception with code "Neo.ClientError.Statement.TypeError" and message "Property values can only be of primitive types or arrays thereof"
```

**Comment by kbsali** [comment]
Sorry about that, we found the issue : we were wrongly sending an  ArrayCollection!

my bad.

**Comment by ikwattro** [comment]
Hi @kbsali Why not having dedicated nodes for roles ?

**Comment by kbsali** [comment]
@ikwattro thanks for the insider-prod tip :),
i guess we are still very relational thinkers! I'll discuss this with the rest of the team!

Thanks
