### ISSUE TITLE
Circular reference

### ISSUE THREAD

**Issue by Nyholm** [graphaware/neo4j-php-ogm#49]
I have an issue where my objects are referenced in a circle. When I try to persist one node we look through all the relationships and all nodes. Which means that they will find more nodes than is originally managed. This will eventually lead to `Maximum function nesting level of '250' reached`. 

![screen shot 2016-11-20 at 15 28 53](https://cloud.githubusercontent.com/assets/1275206/20463564/47aa1b2a-af36-11e6-8e58-e448acd392c3.png)

I think the solution will be to only persist nodes that are new or managed. Never explore unmanaged relations.

**Comment by theUm** [comment]
Also, possible related bug:
if circular reference present ->findAll() method can return duplicate nodes

here`s picture of symfony VarDumper::dump(), purple means that it is same object
![image](https://cloud.githubusercontent.com/assets/3176889/20894850/b2494894-bb1f-11e6-8027-7b3d7a3d1800.png)

here`s code:
![image](https://cloud.githubusercontent.com/assets/3176889/20894923/ff69f5ce-bb1f-11e6-9c0f-e1f9f2325f6b.png)

 here`s db structure:
![image](https://cloud.githubusercontent.com/assets/3176889/20895001/56c0cb40-bb20-11e6-92ea-eb365a143c17.png)

**Comment by theUm** [comment]
Also, in my case I cannot see `Maximum function nesting level of '250' reached`. Instead random related nodes loosing their relations

**Comment by ikwattro** [comment]
@Nyholm @theUm can you confirm fix with latest master please ?

**Comment by Nyholm** [comment]
Im happy to close this. @theUm please test again for dev-master. If you still have this issue, please open a new issue.

**Comment by theUm** [comment]
Wow it seems that everything ok with fetching relations. Much thanks!
I`ll test persistation mechanics with my model for now. I`ll create an issue if I find something.
