### ISSUE TITLE
Implement ObjectManager

### ISSUE THREAD

**Issue by AndrolGenhald** [graphaware/neo4j-php-ogm#5]
Have EntityManager implement ObjectManager so that libraries like DoctrineModule can be used.

**Comment by ikwattro** [comment]
Good idea, was on the roadmap. Gimme a couple of days (heading to AMS for DPCON)

**Comment by ikwattro** [comment]
This has been (partially implemented in the last commits). Leaving this issue open until full implementation

**Comment by Nyholm** [comment]
This can be closed now, right?

**Comment by ikwattro** [comment]
Not sure, need to check the implementation is full.

**Comment by Nyholm** [comment]
No, sorry. I see that there is a lot of TODO's left in the code.
