### ISSUE TITLE
Entity manager constructor bug

### ISSUE THREAD

**Issue by petrosd7** [graphaware/neo4j-php-ogm#50]
When creating a entity manager i get this error

> Argument 1 passed to GraphAware\Neo4j\OGM\EntityManager::__construct() must be an instance of GraphAware\Neo4j\Client\ClientInterface, instance of GraphAware\Neo4j\Client\Client given,

**Comment by Nyholm** [comment]
Make sure you are using `graphaware/neo4j-php-client:^4.6`. The `ClientInterface` was not available in versions before 4.6.0.

**Comment by JoeThielen** [comment]
I ran into this issue as well.  The suggested fix worked, however, probably due to my inexperience with composer and/or other things, I found I had to start from scratch before it would do it for me.  My composer.json:

```
{
    "require": {
        "graphaware/neo4j-php-client": "^4.6",
        "graphaware/neo4j-php-ogm": "^1.0@beta"
    }
}

```

**Comment by JoeThielen** [comment]
I am new to this project, but I've not seen in the main readme nor in the docs/01-intro.md file any mention of requiring the neo4j-php-client... should this be noted in these docs for noobs like myself?  It would have saved me a bit of time and frustration.

**Comment by ikwattro** [comment]
It is an implicit requirement and you shouldn't have to require it yourself. I will investigate further.

**Comment by JoeThielen** [comment]
Perhaps there was an error on my part.  I've started from scratch again and left out the client requirement, and it did work.  I do recall the first time around I had to deal with a missing PHP library (bcmath), so it's quite possible I did not go back and start cleanly.  Thanks for the quick replies and help here!

**Comment by ikwattro** [comment]
Cool to hear!

**Comment by Nyholm** [comment]
Thank you @JoeThielen for bringing up this issue again.

**Comment by JoeThielen** [comment]
No problem, my pleasure.
