### ISSUE TITLE
Transaction is already bound to this session

### ISSUE THREAD

**Issue by ZaphodBBX** [graphaware/neo4j-php-ogm#55]
Hi I'm getting the exception a transaction is already bound to this session when calling an $em->flush();

I have tried adding $em->clear() in several parts of the application but can't seem to solve this.

What could be the reason for this exception?

**Comment by ikwattro** [comment]
Can you please provide your neo4j version and some code ?

**Comment by ZaphodBBX** [comment]
I'm using Neo4j v2.3.1 and Symfony 3.0
I have created a singleton in my application to share the Neo4j connections across my services like this:

`
    final class Morpheus
    {
    
        private $client;
    
        private $entityManager;
    
        /**
         * Private ctor so nobody else can instance it
         * 
         * Morpheus constructor.
         */
        private function __construct($host, $port, $user, $pass)
        {
            $this->client = ClientBuilder::create()
                ->addConnection('default', "http://$user:$pass@$host:$port") //http://neo4j:password@localhost:7474 Example for HTTP connection configuration (port is optional)
                ->build();
    
            $this->entityManager = new NeoEntityManager( $this->client );
    
            return $this;
        }
    
        /**
         * Call this method to get singleton
         *
         * @return UserFactory
         */
        public static function Instance($host, $port, $user, $pass){
            //static definition is set only once.
            //http://php.net/manual/en/language.variables.scope.php#language.variables.scope.static
            static $instance = null;
    
            if ($instance === null){
                $instance = new Morpheus($host, $port, $user, $pass);
            }
    
            return $instance;
        }
        
        /**
         * getNeoClient
         * 
         * @return ClientInterface;
         */
        public function getNeoClient(){
            return $this->client;
        }
    
        /**
         * @return NeoEntityManager
         */
        public function getEntityManager(){
            return $this->entityManager;
        }
    }
`

**Comment by ZaphodBBX** [comment]
I am using Neo4J v2.3.1 and running symfony 3.0

I have created a singleton to share Neo4J client interface and the entity manager across my services like this:

    final class Morpheus
    {
    
        private $client;
    
        private $entityManager;
    
        /**
         * Private ctor so nobody else can instance it
         * 
         * Morpheus constructor.
         */
        private function __construct($host, $port, $user, $pass)
        {
            $this->client = ClientBuilder::create()
                ->addConnection('default', "http://$user:$pass@$host:$port") //http://neo4j:password@localhost:7474 Example for HTTP connection configuration (port is optional)
                ->build();
    
            $this->entityManager = new NeoEntityManager( $this->client );
    
            return $this;
        }
    
        /**
         * Call this method to get singleton
         *
         * @return UserFactory
         */
        public static function Instance($host, $port, $user, $pass){
            //static definition is set only once.
            //http://php.net/manual/en/language.variables.scope.php#language.variables.scope.static
            static $instance = null;
    
            if ($instance === null){
                $instance = new Morpheus($host, $port, $user, $pass);
            }
    
            return $instance;
        }
        
        /**
         * getNeoClient
         * 
         * @return ClientInterface;
         */
        public function getNeoClient(){
            return $this->client;
        }
    
        /**
         * @return NeoEntityManager
         */
        public function getEntityManager(){
            return $this->entityManager;
        }
    }

This works fine when it is injected into 1 service or just in a controller, but the problem arises when multiple services are called that both use this singleton. The exception is not thrown when I reinstantiate the entity manager using a !new Neo4j client connection in each service. But this is exactly what I wanted to avoid by creating the singleton.

**Comment by ikwattro** [comment]
Couldn't reproduce. Please create a repo with a test case. Thanks
