### ISSUE TITLE
Add Relationship creates new node?

### ISSUE THREAD

**Issue by ZaphodBBX** [graphaware/neo4j-php-ogm#56]
A question about the functionality for managing relationships: I have model that is set up very similar to the Actors / Movies model in the example.
When I do something like this:

```
$ActorsRepository = $NeoEntityManager->getRepository(Actors::class);
$actor = $ActorsRepository->findOneBy("name", "Johnny Depp" );
 
$moviesRepository = $NeoEntityManager->getRepository(Movies::class);
$movie = $moviesRepository->findOneBy("title", "Pirates of the Caribbean");

$movie->addActor($actor);
$NeoEntityManager->flush();
```

The lib will try to create a new Actor node with the Johnny Depp node data, where in this situation expected behaviour would be that a relationship is be formed between the 2 existing nodes, without creating a new one right?

**Comment by ikwattro** [comment]
Fixed by #72 

Test here : https://github.com/graphaware/neo4j-php-ogm/blob/master/tests/Integration/MovieDatasetTest.php#L68
