### ISSUE TITLE
Implement Lazy loading or opportunity to load multiple levels of relationships

### ISSUE THREAD

**Issue by sts85** [graphaware/neo4j-php-ogm#6]
When loading entities via the BaseRepository Methods (findOneBy, findAll, ...) the EntityManager only returns the object + the objects directly related to the loaded object.

E.g.: User -> FOLLOWS -> User

Accessing $user->getFollowers()->getFirst()->getFollowers() will return no followers, even though there might be some.

Either implementing lazy loading of these entities or the opportunity to define a depth of how deep relationships shall be followed would highly improve the neo4j-php-ogm

Thanks

**Comment by ikwattro** [comment]
This is on the roadmap actually, should be available during july.

**Comment by sts85** [comment]
Great, I am excited for the new feature. 

It would be useful to be able to set the ordering for to-many relationships as it is possible with doctrine: @OrderBy({"name" = "ASC"})

So if to many relationships are loaded (lazy or not), the ArrayCollection is sorted right away.

**Comment by ikwattro** [comment]
@sts85 There is a first implementation of lazy loading in the just released 1.0.0-beta6. I'll leave the issue open until I find the feature complete.

https://github.com/graphaware/neo4j-php-ogm/blob/master/docs/01-intro.md#lazy-loading

Cheers !

**Comment by ikwattro** [comment]
@sts85 Last beta version contains proxy implementations. OrderBy annotation is still not here though

**Comment by ikwattro** [comment]
@sts85 `OrderBy` annotation implemented on simple relationships for now, example : 

```
<?php

namespace GraphAware\Neo4j\OGM\Tests\Integration\Model;

use Doctrine\Common\Collections\ArrayCollection;
use GraphAware\Neo4j\OGM\Annotations as OGM;

/**
 * @OGM\Node(label="Movie")
 */
class Movie
{
    /**
     * @OGM\GraphId()
     */
    public $id;

    // ...

    /**
     * @OGM\Relationship(targetEntity="Person", type="PLAYED_IN", direction="INCOMING", collection=true, mappedBy="movies")
     * @OGM\OrderBy(property="name", order="ASC")
     */
    public $players;

    public function __construct($title)
    {
        // ...
        $this->players = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getPlayers()
    {
        return $this->players;
    }
}
```

**Comment by sts85** [comment]
Thank you for the implementation!

**Comment by ikwattro** [comment]
@sts85 This is now fully implemented.

You have full proxied entities when needed and order by on both simple relationships and relationship entities, putting some info here while I add it to the docs : 

```
@Relationship(targetEntity="User")
@OrderBy(property="name", order="DESC")
```

For simple relationships (so non-relationship entities), the order by will be defined on the property of the related class, so here `User.name`.

For relationship entities, lets say you have `User`, `Repository` node entities and `Contribution` relationship entity, and you add the order by on the `User::contributions` property : 

`(user:User {name:"john"})-[:CONTRIBUTED_TO {score: 13}]->(repo:Repository {name:"neo4j"})`

```
@OrderBy(property="score", order="ASC")
```

Will perform an ascending order on the `score` property of the `CONTRIBUTED_TO` relationship.

```
@OrderBy(property="repo.name", order="DESC")
```

Will perform a descending order on the name property of the related Repository nodes.

The `repo.name` is representing two things : 

`repo` is the name of the property representing the Repository in your `Contribution` relationship entity class

`name` is the name of the property in the `Repository` class.
