### ISSUE TITLE
Feature: Dynamic labels

### ISSUE THREAD

**Issue by AndrolGenhald** [graphaware/neo4j-php-ogm#9]
I see there is an undocumented `@Label` annotation that can be used with a boolean to include or exclude it. What are your thoughts on having an array that can be used to dynamically set labels? A use case for this would be inheritance:
```
class Foo{
	/**
	 * @OGM\DynamicLabelArray
	 */
	protected $dynamicLabels = [];

	public function __construct(){
		$this->dynamicLabels[] = 'FOO';
	}
}

class Bar extends Foo{
	public function __construct(){
		parent::__construct();
		$this->dynamicLabels[] = 'BAR';
	}
}
```
So all Bar objects would also get the FOO label, and queries using FOO would still match them.
Is this reasonable? Is there a better alternative?

**Comment by ikwattro** [comment]
Hey @AndrolGenhald 

I know inheritance is something that will be needed in the future, I prefer however to focus on having something more stable and tested before tackling that.

However concerning labels, I'm not sure having multiple labels on a same entity would solve a problem of inheritance (at least in a graph). I'm open to any comment and use case, just as I'm working with graphs everyday, I don't see inheritance modeled with multiple labels but rather with relationships : 

```
(animal)<-[:TYPE_OF]-(lion)
```

This is more how I envision the support of class inheritance in the ogm.

Can you maybe describe me your use case where multiple labels in an array should be needed ?

**Comment by AndrolGenhald** [comment]
I've only been using Neo4j for a couple weeks now and I have basically no experience with Cypher, so I'm hardly an authority on the matter.  I was just thinking that, when trying to query all animals that it'd be easier to just use the animal label, rather than a more complex query to find everything in the TYPE_OF chain.
I can see that with deep inheritance trees, 10+ labels would probably not be desirable, and they're probably not the solution to my problem.

My particular use case here is that I'd like users to be able to create relationship types at runtime, so I have a `Relationship` entity with a `type` noncollection relationship to a `Type` entity, and new `Type`s can be created at runtime. My thought was that a user could create a PARENT_OF type and then create FATHER_OF and MOTHER_OF types that "extend" it. Then when querying to find parents, it's much easier to query PARENT_OF instead of PARENT_OF || FATHER_OF || MOTHER_OF. I expect you're right though, and I'm simply trying to do this the wrong way. Feel free to close as won't fix.

**Comment by ikwattro** [comment]
I tend to agree for some use cases on taking the label from the parent class (in a 2 levels inheritance, 3 at max). But definitely not by having it as array property, but taking the label from the parent's class @Node annotation.

Concerning your relationships need, this is interesting. My vision on this (though I don't really use OGM's in production until now but rather with raw Cypher queries), is that your domain entity, let's say "Person", would have a mother and father property, and the `getParents()` method would just aggregate those two properties. Also this handle more easily the use case where one of the parents is unknown. (NB: In your use case, how to differentiate mother from father when querying with PARENT_OF ? - note: filtering on the label is really bad ;-) ).

I will close this issue for now, but feel free to reopen in the future if the need proves to be very generic. I need myself to gain experience on applications with the OGM itself to have a broader vision on the topic, just I can translate domain entity needs to Cypher queries easily).
