### ISSUE TITLE
Do we need EntityManagerInterface::getAnnotationDriver?

### ISSUE THREAD

**Issue by Nyholm** [graphaware/neo4j-php-ogm#91]
It is not implemented and the signature says it should return `\GraphAware\Neo4j\OGM\Mapping\AnnotationDriver` which does not exist.

**Comment by ikwattro** [comment]
Well we need it in order to comply with the EntityManagerInterface. I might change the signature

**Comment by Nyholm** [comment]
Yes, but it is needed in the interface?

**Comment by ikwattro** [comment]
fixed in RC3
