### ISSUE TITLE
Why is Neo4jOGMAnnotations needed?

### ISSUE THREAD

**Issue by Nyholm** [graphaware/neo4j-php-ogm#93]
Doesn't the annotation work without it?

**Comment by ikwattro** [comment]
No annotations are not auto loaded : 

http://docs.doctrine-project.org/projects/doctrine-common/en/latest/reference/annotations.html#registering-annotations

the composer.json autoload the Neo4jOGMAnnotations class :

https://github.com/graphaware/neo4j-php-ogm/blob/master/composer.json#L35

**Comment by Nyholm** [comment]
Okey, thank you.
